name: flutter_voice
description: A voice to text converter app.
# author: Sagnik Ghosh

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  speech_to_text: ^2.5.0
  highlight_text: ^0.7.2
  avatar_glow: ^1.2.0
  
  flutter_launcher_name: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.0


flutter_icons:
  image_path: "icon/icon.jpg" 
  android: true
  ios: true

flutter_launcher_name:
  name: "Voice To Text"

flutter:

  uses-material-design: true
